core/urls.py
from django.urls import path, include
from .views import LandingPageView, ReporteExcel

urlpatterns = [
    path('', LandingPageView.as_view(), name='landing_page'), 
    path('excel/', ReporteExcel.as_view(), name='excel')
]

inventario/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('registration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]



if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include
from .views import ProductCreateView, ProductListView, ProductDetailView, ProductDeleteView, ProductUpdateView

urlpatterns = [
    path('list/', ProductListView.as_view(), name='product_list'),
    path('detail/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='product_update'), 
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'), 
]

registration/urls.py
from django.urls import path, include
from .views import UserCreateView

urlpatterns = [
    path('signup/', UserCreateView.as_view(), name='signup'), 
]

core/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Product(models.Model):
    name = models.CharField(verbose_name="Nombre", max_length=50)
    price = models.IntegerField(verbose_name="Precio")
    information = models.TextField(verbose_name="Información", max_length=500)
    acquisition_date = models.DateTimeField(verbose_name="Fecha de adquisición")
    image = models.ImageField(verbose_name="Imagen", upload_to="products")
    id_user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Usuario", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        ordering = ['acquisition_date']

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from django.forms import widgets
from .models import Product


# form para registrar un producto
class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['name', 'price', 'information', 'acquisition_date', 'image', 'id_user']


# form para actualizar un producto
class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'image', 'price', 'information', 'acquisition_date']

        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Nombre'}),
            # 'image':forms.FileInput(attrs={'class':'form-control', 'style':'height: 70px; padding-top: 38px;', 'placeholder':'Imagen'}),
            'price':forms.NumberInput(attrs={'class':'form-control', 'min':'1000', 'placeholder':'Precio'}),
            'information':forms.Textarea(attrs={'class':'form-control', 'style':'height: 100px;', 'placeholder':'Informacion'}),
            'acquisition_date':forms.DateInput(format ='%Y-%m-%d', attrs={'type':'date','class':'form-control', 'placeholder':'Fecha de adquisicion'}),
        }
        labels = {
            'name':'Nombre',
            'image':'Imagen',
            'price':'Precio',
            'information':'Información',
            'acquisition_date':'Fecha de adquisición',
        }

core/views.py
from django.http import response
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from openpyxl import Workbook
from django.http import request
from django.http.response import HttpResponse
from products.models import Product

# Create your views here.
# landing page
class LandingPageView(TemplateView):
    template_name = "core/landing_page.html"


# generar excel con datos
class ReporteExcel(TemplateView):
    def get(self,request,*args,**kwargs):
        products = Product.objects.filter(id_usuario=self.request.user)
        wb = Workbook()
        ws = wb.active

        ws['B1'] = "Productos"
        ws.merge_cells('B1:C1')
        
        ws['A2'] = "Nombre"
        ws['B2'] = "Precio"
        ws['C2'] = "Información"
        ws['D2'] = "Fecha"

        cont = 3

        for product in products:
            ws.cell(row = cont, column = 1).value = product.nombre
            ws.cell(row = cont, column = 2).value = product.precio
            ws.cell(row = cont, column = 3).value = product.informacion
            ws.cell(row = cont, column = 4).value = str(product.fecha_adquisicion)
            cont += 1
        
        nombre_archivo = "productos.xlsx"
        response = HttpResponse(content_type = "application/ms-excel")
        content = "attachment; filename = {0}".format(nombre_archivo)
        response['Content-Disposition'] = content
        wb.save(response)

        return response

products/views.py
from django.shortcuts import render
from django.http import request 
# ccb
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.urls import reverse_lazy

#requerir login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Product
from .forms import ProductForm, ProductUpdateForm

# Create your views here.

# listar los productos
@method_decorator(login_required, name='dispatch')
class ProductListView(ListView):
    model = Product
    def get_queryset(self):
        return Product.objects.filter(id_user=self.request.user)


# ver cada producto individual
@method_decorator(login_required, name='dispatch')
class ProductDetailView(DetailView):
    model = Product


# crear un producto nuevo
@method_decorator(login_required, name='dispatch')
class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    
    def get_success_url(self):
        return reverse_lazy('product_list')


# actualizar un producto
@method_decorator(login_required, name='dispatch')
class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductUpdateForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('product_list')


# eliminar un producto
@method_decorator(login_required, name='dispatch')
class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('product_list')

core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'landing_page' %}">Mini sistema de información: Administración de productos</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Iniciar sesion</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Registrase</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <div>
        <!-- Content here -->
        {% block content %}{% endblock %}
      </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'landing_page' %}">Mini sistema de información: Administración de productos</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item align-self-center me-3">
                <h5>{{request.user}}</h5>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Cerrar sesion</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <div class="container">
      
      <div class="row">
        <div class="col-8 align-self-center text-center">
          <h1 >{% block titulo %}{% endblock %}</h1>
        </div>
        <div class="col-4 align-self-center text-end">
          <button class="btn btn-link" type="button" onclick="abrir_create_modal('{% url 'product_create' %}')">Agregar productos</button>
          <a class="btn btn-link" href="{% url 'excel' %}">Exportar a excel</a>
        </div>
      </div>

      <!-- Content here -->
      {% block content %}{% endblock %}

      
      <div class="modal fade" id="create_modal" role="dialog">
          
      </div>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    
    <script type="text/javascript">
      var $ = jQuery.noConflict();
      function abrir_create_modal(url){
          $('#create_modal').load(url, function (){
              $(this).modal('show');
          });
      }
    </script>
    {% block extrajs %}{% endblock %}
</body>
</html>

core/templates/core/landing_page.html
{% extends 'core/base.html' %}
{% load staticfiles %}
{% block title %} Landing Page {% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
<script>window.location.href = '/products/list/'; </script>
{% endif %}
<div class="mb-0">
    <img src="{% static 'img/ap.png' %}" class="card-img-top mb-0" alt="imagen del inventario">
    <div class="card-body">
      <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis augue quis lorem sagittis, id sagittis dui ultrices. Mauris cursus, sapien quis venenatis gravida, nulla neque rhoncus turpis, in interdum libero turpis at odio. Proin at felis sit amet est tincidunt consectetur. Phasellus nunc purus, accumsan quis auctor vel, vestibulum eget libero. Nulla neque velit, eleifend non elit non, iaculis efficitur augue. Fusce dignissim, erat vel lobortis rhoncus, nunc enim euismod tellus, eget luctus nunc nibh vestibulum erat. Praesent condimentum viverra tellus, eget congue tellus varius vitae. Donec et felis ligula. Donec tempus arcu quis augue egestas, a vestibulum risus feugiat. Vestibulum scelerisque dolor vel neque laoreet placerat. Curabitur pellentesque lobortis lectus a rutrum. Pellentesque metus nunc, commodo vitae nulla in, rhoncus tempus lectus. Vivamus varius id justo pretium dignissim. Pellentesque molestie ligula ut diam tempus, id faucibus augue pretium. Phasellus eros augue, viverra ultrices metus sed, volutpat vestibulum nisi. Sed volutpat egestas augue, non porttitor justo interdum a.

        Duis pretium justo odio, sed blandit eros dignissim id. Nunc ut pulvinar purus. Donec quis cursus ante, sit amet imperdiet augue. Proin sapien orci, tincidunt ut orci vel, vulputate vehicula enim. Aenean turpis dui, hendrerit ultricies ultricies at, laoreet eget est. Ut vel velit et sapien ornare posuere. Pellentesque facilisis ut mauris quis euismod. Curabitur vitae orci ligula. Curabitur sapien dui, commodo posuere nunc eu, porttitor congue dolor. Donec imperdiet mauris sed est lacinia consequat. Pellentesque eu eros ultricies, sollicitudin nibh varius, congue magna.
        
        Mauris vel massa odio. Integer finibus rhoncus dictum. In feugiat pulvinar lacus, sit amet molestie quam imperdiet ac. Curabitur orci orci, pretium vitae facilisis eu, tincidunt a est. Fusce et gravida libero, et bibendum leo. Etiam viverra id velit vel condimentum. Etiam tincidunt felis lacus, eleifend efficitur lectus elementum quis. Nam erat arcu, sodales eu orci ac, vestibulum finibus leo. Integer volutpat nisl ac vestibulum gravida. Quisque id ipsum mauris. Pellentesque aliquam mattis sapien, et vestibulum neque dictum nec.</p>
    </div>
  </div>
{% endblock %}

products/templates/products/product_confirm_delete.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="detail_modalLabel">Eliminar producto</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'product_delete' object.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="modal-body">
                <p>Está seguro que desea eliminar este producto?</p>
                <p>"{{ object }}"</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-primary">Confirmar</button>
            </div>
        </form>
    </div>
</div>

products/templates/products/product_detail.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="detail_modalLabel">Producto {{ object }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="row justify-content-md-center">
                <div class="col-4">
                    <img src="{{ object.image.url }}" class="img-fluid rounded mx-auto d-block" alt="imagen de {{object.nombre}}">
                </div>
                    <p> {{ object.price }} </p>
                    <p> {{ object.information }} </p>
                    <p> {{ object.acquisition_date|date }} </p>
                
            </div>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>

products/templates/products/product_form.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="detail_modalLabel">Agregar producto</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'product_create' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="modal-body">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %} 
                        <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}

                <div class="form-floating mb-2">
                    <input type="text" name="name" maxlength="50" class="form-control" placeholder="Nombre" required id="id_name">
                    <label for="id_name" class="floatingInput">Nombre</label>
                </div>
                
                <div class="form-floating mb-2">
                    <input type="number" name="price" class="form-control" min="1000" placeholder="Precio" required id="id_price">
                    <label for="id_price" class="floatingInput">Precio</label>
                </div>
                
                <div class="form-floating mb-2">
                    <textarea name="information" style="height: 100px;" maxlength="500" class="form-control" placeholder="Información" required id="id_information"></textarea>
                    <label for="id_information" class="floatingInput">Información</label>
                </div>
                
                <div class="form-floating mb-2">
                    <input type="date" name="acquisition_date" class="form-control" placeholder="Fecha de adquisición" required id="id_acquisition_date">
                    <label for="id_acquisition_date" class="floatingInput">Fecha de adquisición</label>
                </div>
                
                <div class="form-floating mb-2">
                    <input type="file" name="image" style="height: 70px; padding-top: 38px;" accept="image/png,image/jpeg" class="form-control" placeholder="Imagen" required id="id_image">
                    <label for="id_image" class="floatingInput">Imagen</label> 
                </div>
                
                <select name="id_user" hidden=""><option value="{{request.user.id}}" selected>{{request.user}}</option></select>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Agregar</button>
            </div>
        </form>
    </div>
</div>

products/templates/products/product_list.html
{% extends 'core/home.html' %}
{% block title %} Lista de productos {% endblock %}

{% block titulo %}Productos{% endblock %}
{% block content %}
<div class="table-responsive">
    <table class="table">
        <thead class="table-secondary">
            <tr>
              <th scope="col">Nombre</th>
              <th scope="col">Precio</th>
              <th scope="col" colspan="3">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for product in object_list  %}
                <tr>
                    <th scope="row">{{ product.name }}</th>
                    <td>{{ product.price }}</td>
                    
                    <!-- Button trigger modal -->
                    <td>
                        <button type="button" onclick="abrir_detail_modal('{% url 'product_detail' product.id %}')" class="btn btn-outline-success btn-sm">Ver</button>
                    </td>
                    <td>
                        <button type="button" onclick="abrir_update_modal('{% url 'product_update' product.id %}')" class="btn btn-outline-success btn-sm">Actualizar</button>
                    </td>
                    <td>
                        <button type="button" onclick="abrir_delete_modal('{% url 'product_delete' product.id %}')" class="btn btn-outline-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
            {% empty %}
                <li>No hay productos registrados.</li>
            {% endfor %}
        </tbody>
    </table>
    
    <!-- Modal -->
    <div class="modal fade" id="detail_modal" role="dialog">
        
    </div>
    <div class="modal fade" id="update_modal" role="dialog">
        
    </div>
    <div class="modal fade" id="delete_modal" role="dialog">
        
    </div>
</div>

{% endblock %}
{% block extrajs %}
<script type="text/javascript">
    var $ = jQuery.noConflict();
    function abrir_update_modal(url){
        $('#update_modal').load(url, function (){
            $(this).modal('show');
        });
    }
    function abrir_detail_modal(url){
        $('#detail_modal').load(url, function (){
            $(this).modal('show');
        });
    }
    function abrir_delete_modal(url){
        $('#delete_modal').load(url, function (){
            $(this).modal('show');
        });
    }

</script>
{% endblock %}

products/templates/products/product_update_form.html
{% load widget_tweaks %}
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="detail_modalLabel">Actulaizar producto {{ object }}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'product_update' object.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="modal-body">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %} 
                        <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
                {{ form.media}}
                {{ form.as_p }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>
        </form>
    </div>
</div>

            
            